export class StudentsFakeData {
  public static students = [
    {
      id: 1,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-1',
      house: 'Green',
      house_name: 'Somolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 2,
      first_name: 'Maryam',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'B',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 3,
      first_name: 'Maryam',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'A',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 4,
      first_name: 'Maryam',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'A',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 5,
      first_name: 'Maryam',
      surname: 'Bukar',
      date_of_birth: '2021-11-05',
      other_name: 'Yususf',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Yususf',
      parent_surname: 'Bukar',
      parent_other_name: 'Bukar',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/10.png'
    },
    {
      id: 6,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Yususf',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'C',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Yususf',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 7,
      first_name: 'Mike',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Yususf',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 8,
      first_name: 'Mike',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 9,
      first_name: 'Mike',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'C',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/2.png'
    },
    {
      id: 10,
      first_name: 'Mike',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'A',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 11,
      first_name: 'Mike',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Lets See',
      lga: 'Ehen',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/4.png'
    },
    {
      id: 12,
      first_name: 'Mike',
      surname: 'Peter',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Peter',
      parent_other_name: 'Peter',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/5.png'
    },
    {
      id: 13,
      first_name: 'Galen',
      surname: 'Peter',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Peter',
      parent_other_name: 'Peter',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/7.png'
    },
    {
      id: 14,
      first_name: 'Galen',
      surname: 'Peter',
      date_of_birth: '2021-11-05',
      other_name: 'Bashir',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Bashir',
      parent_surname: 'Peter',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 15,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Bashir',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'A',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Bashir',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/2.png'
    },
    {
      id: 16,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Bashir',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-1',
      house: 'Green',
      house_name: 'Somolo House',
      parent_first_name: 'Bashir',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/6.png'
    },
    {
      id: 17,
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Bashir',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-1',
      house: 'Green',
      house_name: 'Somolo House',
      parent_first_name: 'Bashir',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 18,
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'JSS-1',
      house: 'Green',
      house_name: 'Somolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/7.png'
    },
    {
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-1',
      house: 'Green',
      house_name: 'Somolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/6.png'
    },
    {
      id: 21,
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 22,
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/8.png'
    },
    {
      id: 23,
      first_name: 'Nosa',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/3.png'
    },
    {
      id: 24,
      first_name: 'Nosa',
      surname: 'Ahmed',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Ahmed',
      parent_other_name: 'Ahmed',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/2.png'
    },
    {
      id: 25,
      first_name: 'Galen',
      surname: 'Ahmed',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'V',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Ahmed',
      parent_other_name: 'Ahmed',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 26,
      first_name: 'Galen',
      surname: 'Ahmed',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'JSS-2',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Ahmed',
      parent_other_name: 'Ahmed',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/4.png'
    },
    {
      id: 27,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/10.png'
    },
    {
      id: 28,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: ''
    },
    {
      id: 29,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/7.png'
    },
    {
      id: 30,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Blue',
      house_name: 'Mombolo House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: ''
    },
    {
      id: 31,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'C',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 32,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/5.png'
    },
    {
      id: 33,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'A',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/8.png'
    },
    {
      id: 34,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/4.png'
    },
    {
      id: 35,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'SS-1',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 36,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Female',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: ''
    },
    {
      id: 37,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/9.png'
    },
    {
      id: 38,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 39,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: ''
    },
    {
      id: 40,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: 'assets/images/avatars/6.png'
    },
    {
      id: 41,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-2',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Female',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Inactive',
      avatar: ''
    },
    {
      id: 43,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'JSS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 44,
      first_name: 'Abubakar',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 45,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'JSS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/3.png'
    },
    {
      id: 46,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'JSS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 47,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/1.png'
    },
    {
      id: 48,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 49,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'C',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: ''
    },
    {
      id: 50,
      first_name: 'Galen',
      surname: 'Slixby',
      date_of_birth: '2021-11-05',
      other_name: 'Mammu',
      state_of_origin: 'Adamawa',
      lga: 'Mubi',
      gender: 'Male',
      classs_name: 'B',
      classs: 'SS-3',
      house: 'Purple',
      house_name: 'Jere House',
      parent_first_name: 'Mammu',
      parent_surname: 'Slixby',
      parent_other_name: 'Slixby',
      parent_gender: 'Male',
      address: 'Road Skinder PVT Avenue, Gwarinpa',
      parent_phone: '08033464324',
      parent_alt_phone: '08033464324',
      parent_email: 'hredmore1@imgur.com',
      status: 'Active',
      avatar: 'assets/images/avatars/9.png'
    }
  ];
}

export class Student {
  id: number;
  first_name: string;
  surname: string;
  other_name: string;
  state_of_origin: string;
  lga: string;
  gender: string;
  classs_name: string;
  classs: string;
  house: string;
  house_name: string;
  parent_first_name: string;
  parent_surname: string;
  parent_other_name: string;
  parent_gender: string;
  address: string;
  parent_phone: string;
  parent_alt_phone: string;
  parent_email: string;
  status: string;
  avatar: string;
}
